# Generated by Django 5.1.3 on 2024-11-25 15:43

import Booklibrary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('published_date', models.DateField()),
                ('language', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_cover/')),
                ('year', models.PositiveIntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='books/', validators=[Booklibrary.validators.validateDocumentPageLimit])),
            ],
        ),
    ]
